conn SYSTEM/123;

conn S200042133/nafisamaliyat;

DROP TABLE DEPOSITOR_INFO;
DROP TABLE ACCOUNT;
DROP TABLE CUSTOMER;


CREATE TABLE ACCOUNT
(
    ACCOUNT_NO CHAR(5),
    BALANCE NUMBER NOT NULL,
    CONSTRAINT PK_ACCOUNT PRIMARY KEY(ACCOUNT_NO)
);

CREATE TABLE CUSTOMER
(
    CUSTOMER_NO CHAR(5),
    CUSTOMER_NAME VARCHAR2(20) NOT NULL,
    CUSTOMER_CITY VARCHAR2(10),
    CONSTRAINT PK_CUSTOMER PRIMARY KEY(CUSTOMER_NO)
);

CREATE TABLE DEPOSITOR 
(
    ACCOUNT_NO CHAR(5),
    CUSTOMER_NO CHAR(5),
    CONSTRAINT PK_DEPOSITOR PRIMARY KEY(ACCOUNT_NO, CUSTOMER_NO)
);

--2A--
ALTER TABLE CUSTOMER ADD DATE_OF_BIRTH DATE;

--2B--
ALTER TABLE ACCOUNT MODIFY BALANCE NUMBER(12,2);

--2C--
ALTER TABLE DEPOSITOR RENAME COLUMN ACCOUNT_NO TO A_NO;
ALTER TABLE DEPOSITOR RENAME COLUMN CUSTOMER_NO TO C_NO;

--2D--
ALTER TABLE DEPOSITOR RENAME TO DEPOSITOR_INFO;

--2E--
ALTER TABLE DEPOSITOR_INFO 
ADD CONSTRAINT FK_DEPOSITOR_ACCOUNT
FOREIGN KEY (A_NO) REFERENCES 
ACCOUNT(ACCOUNT_NO);

ALTER TABLE DEPOSITOR_INFO 
ADD CONSTRAINT FK_DEPOSITOR_CUSTOMER
FOREIGN KEY (C_NO) REFERENCES 
CUSTOMER(CUSTOMER_NO);


--TEST ENTRIES--
INSERT INTO ACCOUNT VALUES('101', 1000);
INSERT INTO ACCOUNT VALUES('102', 6000);
INSERT INTO ACCOUNT VALUES('103', 10000);
INSERT INTO ACCOUNT VALUES('104', 3000);


INSERT INTO CUSTOMER VALUES('201', 'NAFISA', 'DHK', null);
INSERT INTO CUSTOMER VALUES('202', 'ANIKA', 'KHL', null);
INSERT INTO CUSTOMER VALUES('203', 'MALIYAT', 'KHL', null);
INSERT INTO CUSTOMER VALUES('204', 'AJAY', 'DHK', null);

INSERT INTO DEPOSITOR_INFO VALUES('101', '201');
INSERT INTO DEPOSITOR_INFO VALUES('102', '202');
INSERT INTO DEPOSITOR_INFO VALUES('104', '203');
INSERT INTO DEPOSITOR_INFO VALUES('101', '204');



--QUERIES--

--3A--
SELECT ACCOUNT_NO
FROM ACCOUNT 
WHERE BALANCE<100000;

--3B--
SELECT CUSTOMER_NAME
FROM CUSTOMER 
WHERE CUSTOMER_CITY='KHL';

--3C--
SELECT CUSTOMER_NO
FROM CUSTOMER 
WHERE CUSTOMER_NAME LIKE '%A%';

--3D--
SELECT DISTINCT A_NO
FROM DEPOSITOR_INFO;

--3E-- 
SELECT *
FROM ACCOUNT, DEPOSITOR_INFO;

--3F--
ALTER TABLE DEPOSITOR_INFO RENAME COLUMN C_NO TO CUSTOMER_NO;
SELECT *
FROM CUSTOMER NATURAL JOIN DEPOSITOR_INFO;
ALTER TABLE DEPOSITOR_INFO RENAME COLUMN CUSTOMER_NO TO C_NO;


--3G--
SELECT CUSTOMER.CUSTOMER_NAME, CUSTOMER.CUSTOMER_CITY
FROM DEPOSITOR_INFO, CUSTOMER
WHERE CUSTOMER.CUSTOMER_NO = DEPOSITOR_INFO.C_NO;

--3H--
SELECT CUSTOMER.CUSTOMER_NO, CUSTOMER.CUSTOMER_NAME, CUSTOMER.CUSTOMER_CITY
FROM CUSTOMER
WHERE CUSTOMER_NO IN
(
    SELECT DISTINCT DEPOSITOR_INFO.C_NO
    FROM DEPOSITOR_INFO, ACCOUNT
    WHERE DEPOSITOR_INFO.A_NO = ACCOUNT.ACCOUNT_NO
        AND ACCOUNT.BALANCE>1000
);


--3I--

SELECT DISINCT ACCOUNT.ACCOUNT_NO, ACCOUNT.BALANCE
FROM DEPOSITOR_INFO, ACCOUNT, CUSTOMER
WHERE DEPOSITOR_INFO.A_NO = ACCOUNT.ACCOUNT_NO
    AND DEPOSITOR_INFO.C_NO = CUSTOMER_NO
    AND ACCOUNT.BALANCE>=5000
    AND ACCOUNT.BALANCE<=10000
    AND CUSTOMER.CUSTOMER_CITY='DHK';

